In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('test.csv')
data.head()

,id,comment,product_id,product_title_fa,category_id,category_title_fa,is_buyer
0,1052439,معمولیه و زیاد کیفیتشم خوب نیست ولی در کل زیاد...,3746235,کابل تبدیل USB به microUSB تسکو مدل TC A93 طول...,80,کابل و مبدل,True
1,1130800,جنس خوبی داره با این قدر پول می ارزه,2738072,پایه نگهدارنده گوشی موبایل مدل LS010 مجموعه 8 ...,81,پایه نگهدارنده گوشی و تبلت,True
2,1177330,ایییی بدک نیست,1919416,فلش مموری دی ام مدل PD135 ظرفیت 32 گیگابایت,64,فلش مموری,True
3,1047314,خوبه بااین قیمت بهتر از این نمیشه گرفت,1816187,محافظ صفحه نمایش تراستکتور مدل GSS مناسب برای ...,76,محافظ صفحه نمایش گوشی,True
4,1096710,زیبا بود و ظریف,2158649,جوراب زنانه مدل S855,9841,جوراب زنانه,True

In [3]:
Col = ['comment']
data = data[Col]
data.head()

                                             comment
0  معمولیه و زیاد کیفیتشم خوب نیست ولی در کل زیاد...
1               جنس خوبی داره با این قدر پول می ارزه
2                                     ایییی بدک نیست
3             خوبه بااین قیمت بهتر از این نمیشه گرفت
4                                    زیبا بود و ظریف

In [5]:
data['comment'] = data['comment'].apply(lambda x : len(x.split()))
data.head()

   comment
0       12
1        9
2        3
3        8
4        4